### ISSUE TITLE
Runtime exception: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by tballison** [trailofbits/polyfile#13]
`
[Traceback (most recent call last):,   File "/usr/local/bin/polyfile", line 11, in <module>,     load_entry_point('polyfile', 'console_scripts', 'polyfile')(),   File "/Users/allison/Documents/tob/polyfile/__main__.py", line 72, in main,     for match in matcher.match(file_path, progress_callback=progress_callback):,   File "/Users/allison/Documents/tob/polyfile/polyfile.py", line 170, in match,     yield from submatch_iter,   File "/Users/allison/Documents/tob/polyfile/pdf.py", line 288, in submatch,     yield from parse_pdf(file_stream, matcher=self.matcher, parent=self),   File "/Users/allison/Documents/tob/polyfile/pdf.py", line 282, in parse_pdf,     yield from parse_object(file_stream, object, matcher=matcher, parent=parent),   File "/Users/allison/Documents/tob/polyfile/pdf.py", line 126, in parse_object,     oPDFParseDictionary = pdfparser.cPDFParseDictionary(object.content, False),   File "/Users/allison/Documents/tob/polyfile/pdfparser.py", line 844, in __init__,     self.parsed = self.ParseDictionary(dataTrimmed)[0], TypeError: 'NoneType' object is not subscriptable]
`

govdocs/706/706211.pdf

Let me know if I should attach the triggering file.

**Comment by ESultanik** [comment]
Fixed. Verified on v0.5.6 (commit f1ce8d9) against `govdocs1/706/706211.pdf`.

`cPDFParseDictionary.__init__` lived in the vendored copy of Didier Stevens' `pdfparser.py`,
which commit 88f915c (2022-02-10) deleted when PDF handling moved to `pdfminer.six`. The
`self.parsed = self.ParseDictionary(dataTrimmed)[0]` line no longer exists.

`706211.pdf` parses to 11,733 nodes across 243 `PDFObject`s, exit status 0, no warnings.

No need to attach the file — it is still available from the govdocs1 corpus. Closing.
