### ISSUE TITLE
Cannot unpack non-iterable NoneType

### ISSUE THREAD

**Issue by tballison** [trailofbits/polyfile#14]
`[Traceback (most recent call last):,   File "/usr/local/bin/polyfile", line 11, in <module>,     load_entry_point('polyfile', 'console_scripts', 'polyfile')(),   File "/Users/allison/Documents/tob/polyfile/__main__.py", line 72, in main,     for match in matcher.match(file_path, progress_callback=progress_callback):,   File "/Users/allison/Documents/tob/polyfile/polyfile.py", line 170, in match,     yield from submatch_iter,   File "/Users/allison/Documents/tob/polyfile/pdf.py", line 288, in submatch,     yield from parse_pdf(file_stream, matcher=self.matcher, parent=self),   File "/Users/allison/Documents/tob/polyfile/pdf.py", line 282, in parse_pdf,     yield from parse_object(file_stream, object, matcher=matcher, parent=parent),   File "/Users/allison/Documents/tob/polyfile/pdf.py", line 126, in parse_object,     oPDFParseDictionary = pdfparser.cPDFParseDictionary(object.content, False),   File "/Users/allison/Documents/tob/polyfile/pdfparser.py", line 844, in __init__,     self.parsed = self.ParseDictionary(dataTrimmed)[0],   File "/Users/allison/Documents/tob/polyfile/pdfparser.py", line 881, in ParseDictionary,     value, tokens = self.ParseDictionary(tokens), TypeError: cannot unpack non-iterable NoneType object]`

triggering file: govdocs/810/810124.pdf

**Comment by ESultanik** [comment]
Fixed. Verified on v0.5.6 (commit f1ce8d9) against `govdocs1/810/810124.pdf`.

`cPDFParseDictionary.ParseDictionary` lived in the vendored copy of Didier Stevens'
`pdfparser.py`, which commit 88f915c (2022-02-10) deleted when PDF handling moved to
`pdfminer.six`. Dictionary construction is now driven by pdfminer's `PSStackParser` state
machine, so the recursive call that could return `None` is gone.

`810124.pdf` parses to 2,602 nodes across 79 `PDFObject`s, exit status 0, no warnings.

Closing.
