### ISSUE TITLE
UnboundLocalError: local variable 'is_dct_decode' referenced before assignment

### ISSUE THREAD

**Issue by tballison** [trailofbits/polyfile#15]
` [Traceback (most recent call last):,   File "/usr/local/bin/polyfile", line 11, in <module>,     load_entry_point('polyfile', 'console_scripts', 'polyfile')(),   File "/Users/allison/Documents/tob/polyfile/__main__.py", line 72, in main,     for match in matcher.match(file_path, progress_callback=progress_callback):,   File "/Users/allison/Documents/tob/polyfile/polyfile.py", line 170, in match,     yield from submatch_iter,   File "/Users/allison/Documents/tob/polyfile/pdf.py", line 288, in submatch,     yield from parse_pdf(file_stream, matcher=self.matcher, parent=self),   File "/Users/allison/Documents/tob/polyfile/pdf.py", line 282, in parse_pdf,     yield from parse_object(file_stream, object, matcher=matcher, parent=parent),   File "/Users/allison/Documents/tob/polyfile/pdf.py", line 208, in parse_object,     if is_dct_decode and raw_content[:1] == b'\xff':, UnboundLocalError: local variable 'is_dct_decode' referenced before assignment`

triggering file: common_crawl/6fb/9cc/eb3/6fb9cceb33a2bf98749e895e43840e90f4bcbf4a631b512c010675e3763f5433

**Comment by tballison** [comment]
[6fb9cceb33a2bf98749e895e43840e90f4bcbf4a631b512c010675e3763f5433.pdf](https://github.com/trailofbits/polyfile/files/3871096/6fb9cceb33a2bf98749e895e43840e90f4bcbf4a631b512c010675e3763f5433.pdf)

**Comment by ESultanik** [comment]
Fixed. Verified on v0.5.6 (commit f1ce8d9) against the file @tballison attached.

`is_dct_decode` was first patched in commit f224491 (2019-12-04), which initialized it before
the branch that read it. The variable was then removed entirely in commit 9652cbf
(2020-10-26), which modularized the PDF stream filters. DCT streams are now recognized in
`PDFObjectStream.decode` (`polyfile/pdf.py:639-643`) and passed through undecoded, since a
JPEG stream does not need a second decoding pass.

Your file contains one `/DCTDecode` stream. On v0.5.6 it parses to 818 nodes across 20
`PDFObject`s, with exit status 0 and no warnings.

Closing.
