### ISSUE TITLE
in unget, assert isinstance(byte, PDFByte), AssertionError]

### ISSUE THREAD

**Issue by tballison** [trailofbits/polyfile#16]
`[Traceback (most recent call last):,   File "/usr/local/bin/polyfile", line 11, in <module>,     load_entry_point('polyfile', 'console_scripts', 'polyfile')(),   File "/Users/allison/Documents/tob/polyfile/__main__.py", line 72, in main,     for match in matcher.match(file_path, progress_callback=progress_callback):,   File "/Users/allison/Documents/tob/polyfile/polyfile.py", line 170, in match,     yield from submatch_iter,   File "/Users/allison/Documents/tob/polyfile/pdf.py", line 288, in submatch,     yield from parse_pdf(file_stream, matcher=self.matcher, parent=self),   File "/Users/allison/Documents/tob/polyfile/pdf.py", line 243, in parse_pdf,     object = parser.GetObject(),   File "/Users/allison/Documents/tob/polyfile/pdfparser.py", line 426, in GetObject,     self.token = self.oPDFTokenizer.TokenIgnoreWhiteSpace(),   File "/Users/allison/Documents/tob/polyfile/pdfparser.py", line 396, in TokenIgnoreWhiteSpace,     token = self.Token(),   File "/Users/allison/Documents/tob/polyfile/pdfparser.py", line 373, in Token,     self.oPDF.unget(self.byte),   File "/Users/allison/Documents/tob/polyfile/pdfparser.py", line 240, in unget,     assert isinstance(byte, PDFByte), AssertionError]`

File: govdocs/176/176361.pdf

**Comment by ESultanik** [comment]
This was likely fixed by virtue of switching PDF parser implementations. We will confirm and, if so, close this issue.

**Comment by ESultanik** [comment]
Fixed. Verified on v0.5.6 (commit f1ce8d9) against `govdocs1/176/176361.pdf`.

`unget` and its `assert isinstance(byte, PDFByte)` lived in the vendored copy of Didier
Stevens' `pdfparser.py`, deleted in commit 88f915c (2022-02-10) when PDF handling moved to
`pdfminer.six`. Neither `unget` nor `PDFByte` exists anywhere in the tree now.

`176361.pdf` (3.2 MB) parses to 15,952 nodes across 291 `PDFObject`s, exit status 0, no
warnings.

Closing.
