### ISSUE TITLE
Two crashes when parsing PDFs

### ISSUE THREAD

**Issue by TACIXAT** [trailofbits/polyfile#26]
Govdocs - 

[000899.pdf](https://github.com/trailofbits/polyfile/files/4882183/000899.pdf)
[001940.pdf](https://github.com/trailofbits/polyfile/files/4882184/001940.pdf)

```
Parsing PDF obj 62 0Traceback (most recent call last):
  File "/usr/local/bin/polyfile", line 11, in <module>
    load_entry_point('polyfile===0.1.6-git', 'console_scripts', 'polyfile')()
  File "/home/taxicat/.local/lib/python3.6/site-packages/polyfile-0.1.6_git-py3.6.egg/polyfile/__main__.py", line 99, in main
    for match in matcher.match(file_path, progress_callback=progress_callback, trid_defs=trid_defs):
  File "/home/taxicat/.local/lib/python3.6/site-packages/polyfile-0.1.6_git-py3.6.egg/polyfile/polyfile.py", line 178, in match
    yield from submatch_iter
  File "/home/taxicat/.local/lib/python3.6/site-packages/polyfile-0.1.6_git-py3.6.egg/polyfile/pdf.py", line 296, in submatch
    yield from parse_pdf(file_stream, matcher=self.matcher, parent=self)
  File "/home/taxicat/.local/lib/python3.6/site-packages/polyfile-0.1.6_git-py3.6.egg/polyfile/pdf.py", line 290, in parse_pdf
    yield from parse_object(file_stream, object, matcher=matcher, parent=parent)
  File "/home/taxicat/.local/lib/python3.6/site-packages/polyfile-0.1.6_git-py3.6.egg/polyfile/pdf.py", line 118, in parse_object
    yield from _emit_dict(oPDFParseDictionary.parsed, obj, parent.offset)
  File "/home/taxicat/.local/lib/python3.6/site-packages/polyfile-0.1.6_git-py3.6.egg/polyfile/pdf.py", line 38, in _emit_dict
    value_end = value[-1].offset.offset + len(value[-1].token)
IndexError: list index out of range
```

```
Parsing PDF obj 424 0Traceback (most recent call last):
  File "/usr/local/bin/polyfile", line 11, in <module>
    load_entry_point('polyfile===0.1.6-git', 'console_scripts', 'polyfile')()
  File "/home/taxicat/.local/lib/python3.6/site-packages/polyfile-0.1.6_git-py3.6.egg/polyfile/__main__.py", line 99, in main
    for match in matcher.match(file_path, progress_callback=progress_callback, trid_defs=trid_defs):
  File "/home/taxicat/.local/lib/python3.6/site-packages/polyfile-0.1.6_git-py3.6.egg/polyfile/polyfile.py", line 178, in match
    yield from submatch_iter
  File "/home/taxicat/.local/lib/python3.6/site-packages/polyfile-0.1.6_git-py3.6.egg/polyfile/pdf.py", line 296, in submatch
    yield from parse_pdf(file_stream, matcher=self.matcher, parent=self)
  File "/home/taxicat/.local/lib/python3.6/site-packages/polyfile-0.1.6_git-py3.6.egg/polyfile/pdf.py", line 290, in parse_pdf
    yield from parse_object(file_stream, object, matcher=matcher, parent=parent)
  File "/home/taxicat/.local/lib/python3.6/site-packages/polyfile-0.1.6_git-py3.6.egg/polyfile/pdf.py", line 118, in parse_object
    yield from _emit_dict(oPDFParseDictionary.parsed, obj, parent.offset)
  File "/home/taxicat/.local/lib/python3.6/site-packages/polyfile-0.1.6_git-py3.6.egg/polyfile/pdf.py", line 61, in _emit_dict
    ''.join(v.token for v in value),
  File "/home/taxicat/.local/lib/python3.6/site-packages/polyfile-0.1.6_git-py3.6.egg/polyfile/pdf.py", line 61, in <genexpr>
    ''.join(v.token for v in value),
AttributeError: 'str' object has no attribute 'token'
```

**Comment by nealmcb** [comment]
I saw the latter bug also, on the first file I tried it on (a big one that I think was generated from a docx file), under Python 3.8: `AttributeError: 'str' object has no attribute 'token'`

**Comment by ESultanik** [comment]
This was likely fixed by switching PDF parser implementations. We will confirm and close if that is the case.

**Comment by ESultanik** [comment]
Fixed. Verified on v0.5.6 (commit f1ce8d9, Python 3.14.0) against both files you attached.

Both crashes were in `_emit_dict` in the old `polyfile/pdf.py`, which sat on top of the
vendored copy of Didier Stevens' `pdfparser.py`. Commit 88f915c (2022-02-10) deleted that
parser and rebuilt PDF handling on `pdfminer.six`; `_emit_dict` no longer exists. The
current dictionary walk explicitly handles both failure modes you hit — an empty list
(`polyfile/pdf.py:883-886`) and a value that carries no byte provenance
(`polyfile/pdf.py:894-897`) are logged and skipped instead of crashing.

Results:

| file | exit | warnings | nodes parsed |
|---|---|---|---|
| `000899.pdf` | 0 | none | 6,821 |
| `001940.pdf` | 0 | none | 19,538 |

Both produce a full structure tree (254 and 498 `PDFObject` nodes respectively), so this is
a real parse, not an empty result.

@nealmcb, the `AttributeError: 'str' object has no attribute 'token'` you saw on 0.1.7 came
from the same deleted function. If a current release still fails on your file, please open a
new issue with it attached.

Closing.
