### ISSUE TITLE
Readline missing from setup.py?

### ISSUE THREAD

**Issue by ross-spencer** [trailofbits/polyfile#3367]
Trying to install this fresh on a Windows box today. 

```bash
Traceback (most recent call last):
  File "C:\Users\Spencer\Apps\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Spencer\Apps\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Spencer\Apps\python\Scripts\polyfile.exe\__main__.py", line 4, in <module>
  File "C:\Users\Spencer\Apps\python\lib\site-packages\polyfile\__init__.py", line 2, in <module>
    from .__main__ import main
  File "C:\Users\Spencer\Apps\python\lib\site-packages\polyfile\__main__.py", line 18, in <module>
    from .debugger import Debugger
  File "C:\Users\Spencer\Apps\python\lib\site-packages\polyfile\debugger.py", line 12, in <module>
    from .repl import ANSIColor, ANSIWriter, arg_completer, command, ExitREPL, log, REPL, SetCompleter
  File "C:\Users\Spencer\Apps\python\lib\site-packages\polyfile\repl.py", line 7, in <module>
    import readline
ModuleNotFoundError: No module named 'readline'
```

It looks like `readline` is a [new requirement](https://github.com/trailofbits/polyfile/commit/ce7d630a243069bede162a397dd98ff3612f97f7) and isn't listed in the requirements: https://github.com/trailofbits/polyfile/blob/9c2d20b0013c670e36e8051cfbb3199f9f36d762/setup.py#L123-L134 

Pip version: `pip 21.3.1 from C:\Users\Spencer\Apps\python\lib\site-packages\pip (python 3.9)`

**Comment by ESultanik** [comment]
Curious, `readline` has been [bundled with Python since at least version 3.6](https://docs.python.org/3.6/library/readline.html), and the documentation doesn't mention any restrictions with OS 🤔. We haven't had any issues on macOS or Linux, so I suspect this is a Windows issue. I'm going to try adding support for Windows via https://github.com/pyreadline3/pyreadline3

**Comment by ESultanik** [comment]
PolyFile v0.4.1 should now support Windows. @ross-spencer are you able to confirm that this resolved your issues?

**Comment by ESultanik** [comment]
Fixed in v0.4.1 and verified again on v0.5.6 (commit f1ce8d9).

`readline` is a standard-library module on macOS and Linux but not on Windows, so the
import in `polyfile/repl.py` failed there. Two commits addressed it:

- f1b007a added `pyreadline3;platform_system=='Windows'` to `install_requires`, and
  `polyfile/repl.py` now selects the implementation at import time:

  ```python
  try:
      import readline
  except ModuleNotFoundError:
      import pyreadline3 as readline
  ```

- fb78915 added Windows to the CI matrix.

One caveat worth recording: the Windows and macOS runners were later commented out of
`.github/workflows/tests.yml`, so the suite currently runs on `ubuntu-latest` only. The
dependency and the import guard are both still in place, but Windows is not exercised
continuously.

Closing. If you still hit this on a current release, reopen with the `pip --version` and
`python --version` output and I will take another look.
